#THIS IS THE MAIN SCRIPT FOR BUILDING THIS SCRIPT SHOULD BE IN THE HAVOC FOLDER NOT IN ANY SUB FOLDERS
#INTIATE SCRIPT SHOULD AUTOMATICALLY PULL THIS SCRIPT BACK TO HAVOC FOLDER

. 1.sh
. 2.sh
. 3.sh
. 4.sh
. upload.sh
